### ISSUE TITLE
[BUG] License actually claims Yelp owns the copyright

### ISSUE THREAD

**Issue by blu3mania** [IBM/detect-secrets#1]
**Describe the bug**
In LICENSE, it claims Yelp is the copyright owner, which can't be correct, right?
> Copyright 2017-2018 Yelp Inc.

**Comment by killuazhu** [comment]
This repo is forked from https://github.com/Yelp/detect-secrets and licensed under Apache 2.0. We would need to preserve the copyright and license notices.
